import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Transportation from './models/Transportation.js';
import connectDB from './config/db.js';

dotenv.config({ path: './.env' });
await connectDB();

const seedData = [
  // ─── FLIGHTS (6) ────────────────────────────────────────────────
  { mode:'Flight',operator:'IndiGo',from:'Delhi',to:'Mumbai',departureTime:'06:00',arrivalTime:'08:15',duration:'2h 15m',price:3499,originalPrice:4999,rating:4.3,reviews:2340,vehicleType:'Airbus A320neo',seats:180,seatsAvailable:12,luggage:15,luxuryLevel:'Standard',comfortLevel:'Economy',facilities:['AC','Wi-Fi','Charging Port','Food'],routeType:'Direct',groupType:['Solo','Couple','Corporate'],badge:'Cheapest',image:'https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=800',description:'Budget-friendly direct flight with complimentary snacks and Wi-Fi.',featured:true,availabilityDate:new Date('2026-06-15'),gallery:['https://images.unsplash.com/photo-1436491865332-7a61a109db05?w=800']},
  { mode:'Flight',operator:'Vistara',from:'Mumbai',to:'Goa',departureTime:'10:30',arrivalTime:'11:45',duration:'1h 15m',price:5299,originalPrice:6999,rating:4.7,reviews:1890,vehicleType:'Boeing 737-800',seats:168,seatsAvailable:5,luggage:25,luxuryLevel:'Premium',comfortLevel:'Business',facilities:['AC','Wi-Fi','Food','Charging Port','Luggage'],routeType:'Direct',groupType:['Solo','Couple','Friends'],badge:'Fastest',image:'https://images.unsplash.com/photo-1556388158-158ea5ccacbd?w=800',description:'Premium business class experience with gourmet meals and extra legroom.',featured:true,availabilityDate:new Date('2026-06-20'),gallery:[]},
  { mode:'Flight',operator:'Air India',from:'Delhi',to:'Jaipur',departureTime:'14:00',arrivalTime:'15:10',duration:'1h 10m',price:2999,originalPrice:3999,rating:4.1,reviews:1200,vehicleType:'Airbus A319',seats:144,seatsAvailable:30,luggage:20,luxuryLevel:'Standard',comfortLevel:'Economy',facilities:['AC','Food','Luggage'],routeType:'Direct',groupType:['Solo','Family','Corporate'],badge:null,image:'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?w=800',description:'Convenient direct flight to the Pink City.',availabilityDate:new Date('2026-06-25'),gallery:[]},
  { mode:'Flight',operator:'SpiceJet',from:'Bangalore',to:'Hyderabad',departureTime:'07:30',arrivalTime:'08:45',duration:'1h 15m',price:2799,originalPrice:3499,rating:4.0,reviews:980,vehicleType:'Boeing 737 MAX',seats:189,seatsAvailable:45,luggage:15,luxuryLevel:'Standard',comfortLevel:'Economy',facilities:['AC','Charging Port'],routeType:'Direct',groupType:['Solo','Corporate'],badge:'Cheapest',image:'https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=800',description:'Early morning shuttle between tech hubs.',availabilityDate:new Date('2026-07-01'),gallery:[]},
  { mode:'Flight',operator:'Vistara',from:'Delhi',to:'Goa',departureTime:'09:00',arrivalTime:'11:30',duration:'2h 30m',price:7999,originalPrice:10999,rating:4.8,reviews:3200,vehicleType:'Boeing 787 Dreamliner',seats:256,seatsAvailable:3,luggage:30,luxuryLevel:'Luxury',comfortLevel:'First Class',facilities:['AC','Wi-Fi','Food','Charging Port','Luggage','Sleeper'],routeType:'Direct',groupType:['Couple','Friends'],badge:'Luxury Pick',image:'https://images.unsplash.com/photo-1540339832862-474599807836?w=800',description:'First class luxury with lie-flat seats and premium lounge access.',featured:true,availabilityDate:new Date('2026-06-18'),gallery:[]},
  { mode:'Flight',operator:'IndiGo',from:'Chennai',to:'Kolkata',departureTime:'16:00',arrivalTime:'18:30',duration:'2h 30m',price:4199,originalPrice:5499,rating:4.2,reviews:1560,vehicleType:'Airbus A321neo',seats:222,seatsAvailable:18,luggage:15,luxuryLevel:'Standard',comfortLevel:'Economy',facilities:['AC','Wi-Fi','Charging Port'],routeType:'One Stop',groupType:['Solo','Corporate'],badge:null,image:'https://images.unsplash.com/photo-1529074097478-3b5541ecb900?w=800',description:'Connecting flight via Visakhapatnam with short layover.',availabilityDate:new Date('2026-07-05'),gallery:[]},

  // ─── TRAINS (6) ────────────────────────────────────────────────
  { mode:'Train',operator:'Rajdhani Express',from:'Delhi',to:'Mumbai',departureTime:'16:55',arrivalTime:'08:35',duration:'15h 40m',price:1899,originalPrice:2499,rating:4.5,reviews:5200,vehicleType:'Superfast Express',seats:72,seatsAvailable:8,luggage:40,luxuryLevel:'Premium',comfortLevel:'Standard',facilities:['AC','Food','Charging Port','Sleeper','Luggage'],routeType:'Direct',groupType:['Solo','Family','Friends','Corporate'],badge:'Best Value',image:'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800',description:'India\'s premier overnight express with meals included.',featured:true,availabilityDate:new Date('2026-06-10'),gallery:[]},
  { mode:'Train',operator:'Shatabdi Express',from:'Delhi',to:'Jaipur',departureTime:'06:05',arrivalTime:'10:30',duration:'4h 25m',price:899,originalPrice:1199,rating:4.4,reviews:4100,vehicleType:'Chair Car Express',seats:78,seatsAvailable:22,luggage:30,luxuryLevel:'Standard',comfortLevel:'Standard',facilities:['AC','Food','Charging Port'],routeType:'Direct',groupType:['Solo','Couple','Corporate'],badge:'Cheapest',image:'https://images.unsplash.com/photo-1532105956626-9569c03602f6?w=800',description:'Morning express to Jaipur with complimentary breakfast.',availabilityDate:new Date('2026-06-12'),gallery:[]},
  { mode:'Train',operator:'Vande Bharat',from:'Mumbai',to:'Goa',departureTime:'05:40',arrivalTime:'13:30',duration:'7h 50m',price:1599,originalPrice:1999,rating:4.6,reviews:3800,vehicleType:'Semi-High Speed',seats:78,seatsAvailable:15,luggage:35,luxuryLevel:'Premium',comfortLevel:'Business',facilities:['AC','Wi-Fi','Food','Charging Port','Luggage'],routeType:'One Stop',groupType:['Family','Friends','Couple'],badge:'Fastest',image:'https://images.unsplash.com/photo-1504289824481-dc05f5c25ad0?w=800',description:'India\'s fastest semi-high-speed train with world-class amenities.',featured:true,availabilityDate:new Date('2026-06-22'),gallery:[]},
  { mode:'Train',operator:'Duronto Express',from:'Bangalore',to:'Delhi',departureTime:'20:00',arrivalTime:'06:00',duration:'34h',price:2299,originalPrice:2899,rating:4.3,reviews:2100,vehicleType:'Non-Stop Express',seats:54,seatsAvailable:6,luggage:50,luxuryLevel:'Premium',comfortLevel:'Standard',facilities:['AC','Food','Sleeper','Luggage'],routeType:'Direct',groupType:['Solo','Family'],badge:null,image:'https://images.unsplash.com/photo-1515005318787-cc68052b38f3?w=800',description:'Non-stop overnight journey with sleeper class comfort.',availabilityDate:new Date('2026-07-02'),gallery:[]},
  { mode:'Train',operator:'Garib Rath',from:'Delhi',to:'Kolkata',departureTime:'15:20',arrivalTime:'08:10',duration:'16h 50m',price:699,originalPrice:999,rating:3.8,reviews:6700,vehicleType:'AC 3-Tier',seats:72,seatsAvailable:40,luggage:30,luxuryLevel:'Standard',comfortLevel:'Economy',facilities:['AC','Sleeper'],routeType:'Multi-Stop',groupType:['Solo','Friends'],badge:'Cheapest',image:'https://images.unsplash.com/photo-1498693313395-1940ad8a1585?w=800',description:'Most affordable AC sleeper option for budget travelers.',availabilityDate:new Date('2026-06-28'),gallery:[]},
  { mode:'Train',operator:'Maharaja Express',from:'Delhi',to:'Jaipur',departureTime:'09:00',arrivalTime:'15:30',duration:'6h 30m',price:15999,originalPrice:19999,rating:4.9,reviews:890,vehicleType:'Luxury Tourist Train',seats:20,seatsAvailable:2,luggage:60,luxuryLevel:'Ultra Luxury',comfortLevel:'Luxury',facilities:['AC','Wi-Fi','Food','Charging Port','Sleeper','Luggage','Pet Friendly'],routeType:'Direct',groupType:['Couple','Family'],badge:'Luxury Pick',image:'https://images.unsplash.com/photo-1520939817895-060bdaf4fe1b?w=800',description:'Royal luxury train experience with butler service and fine dining.',featured:true,availabilityDate:new Date('2026-06-16'),gallery:[]},

  // ─── BUSES (5) ─────────────────────────────────────────────────
  { mode:'Bus',operator:'Volvo RedBus',from:'Bangalore',to:'Goa',departureTime:'22:00',arrivalTime:'06:30',duration:'8h 30m',price:999,originalPrice:1499,rating:4.2,reviews:3400,vehicleType:'Multi-Axle Volvo',seats:40,seatsAvailable:10,luggage:20,luxuryLevel:'Standard',comfortLevel:'Standard',facilities:['AC','Wi-Fi','Charging Port','Sleeper'],routeType:'Direct',groupType:['Solo','Friends','Couple'],badge:'Best Value',image:'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800',description:'Overnight sleeper Volvo with entertainment screens.',availabilityDate:new Date('2026-06-14'),gallery:[]},
  { mode:'Bus',operator:'SRS Travels',from:'Mumbai',to:'Goa',departureTime:'20:00',arrivalTime:'06:00',duration:'10h',price:799,originalPrice:1099,rating:3.9,reviews:2800,vehicleType:'Sleeper Coach',seats:36,seatsAvailable:20,luggage:15,luxuryLevel:'Standard',comfortLevel:'Economy',facilities:['AC','Sleeper'],routeType:'Multi-Stop',groupType:['Solo','Friends'],badge:'Cheapest',image:'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800',description:'Budget overnight sleeper bus with multiple boarding points.',availabilityDate:new Date('2026-06-19'),gallery:[]},
  { mode:'Bus',operator:'Orange Tours',from:'Hyderabad',to:'Bangalore',departureTime:'21:30',arrivalTime:'05:45',duration:'8h 15m',price:1199,originalPrice:1599,rating:4.4,reviews:2100,vehicleType:'Mercedes Multi-Axle',seats:32,seatsAvailable:7,luggage:25,luxuryLevel:'Premium',comfortLevel:'Business',facilities:['AC','Wi-Fi','Charging Port','Sleeper','Food'],routeType:'Direct',groupType:['Solo','Corporate','Friends'],badge:'Fastest',image:'https://images.unsplash.com/photo-1557223562-6c77ef16210f?w=800',description:'Premium Mercedes coach with recliner seats and snacks.',availabilityDate:new Date('2026-07-03'),gallery:[]},
  { mode:'Bus',operator:'KSRTC Airavat',from:'Bangalore',to:'Chennai',departureTime:'23:00',arrivalTime:'05:30',duration:'6h 30m',price:599,originalPrice:799,rating:4.1,reviews:5600,vehicleType:'Club Class',seats:45,seatsAvailable:25,luggage:15,luxuryLevel:'Standard',comfortLevel:'Economy',facilities:['AC','Charging Port'],routeType:'Direct',groupType:['Solo','Corporate'],badge:null,image:'https://images.unsplash.com/photo-1464219789935-c2d9d9aba644?w=800',description:'Government-run AC seater bus, punctual and reliable.',availabilityDate:new Date('2026-06-30'),gallery:[]},
  { mode:'Bus',operator:'Luxury Liner',from:'Delhi',to:'Manali',departureTime:'18:00',arrivalTime:'06:00',duration:'12h',price:1599,originalPrice:2299,rating:4.5,reviews:1900,vehicleType:'2+1 Luxury Sleeper',seats:24,seatsAvailable:4,luggage:30,luxuryLevel:'Premium',comfortLevel:'Business',facilities:['AC','Wi-Fi','Charging Port','Sleeper','Food','Luggage'],routeType:'Multi-Stop',groupType:['Friends','Family','Couple'],badge:'Family Friendly',image:'https://images.unsplash.com/photo-1516738901171-8eb4fc13bd20?w=800',description:'Premium 2+1 sleeper to the mountains with snack box and blankets.',availabilityDate:new Date('2026-07-10'),gallery:[]},

  // ─── CABS (4) ──────────────────────────────────────────────────
  { mode:'Cab',operator:'Ola Outstation',from:'Delhi',to:'Agra',departureTime:'Flexible',arrivalTime:'~4h',duration:'3h 30m',price:2499,originalPrice:3199,rating:4.3,reviews:1800,vehicleType:'Toyota Innova Crysta',seats:6,seatsAvailable:6,luggage:4,luxuryLevel:'Premium',comfortLevel:'Standard',facilities:['AC','Charging Port','Luggage'],routeType:'Direct',groupType:['Family','Friends','Couple'],badge:'Family Friendly',image:'https://images.unsplash.com/photo-1449965408869-ebd13bc0c322?w=800',description:'Comfortable outstation cab with experienced driver and flexible stops.',availabilityDate:new Date('2026-06-11'),gallery:[]},
  { mode:'Cab',operator:'Uber Premium',from:'Mumbai',to:'Pune',departureTime:'Flexible',arrivalTime:'~3.5h',duration:'3h',price:3299,originalPrice:3999,rating:4.6,reviews:2400,vehicleType:'BMW 5 Series',seats:4,seatsAvailable:4,luggage:3,luxuryLevel:'Luxury',comfortLevel:'Luxury',facilities:['AC','Wi-Fi','Charging Port','Food'],routeType:'Direct',groupType:['Couple','Corporate'],badge:'Luxury Pick',image:'https://images.unsplash.com/photo-1549317661-bd32c8ce0afa?w=800',description:'Chauffeur-driven luxury sedan with refreshments and Wi-Fi.',featured:true,availabilityDate:new Date('2026-06-17'),gallery:[]},
  { mode:'Cab',operator:'Meru Cabs',from:'Bangalore',to:'Mysore',departureTime:'Flexible',arrivalTime:'~3h',duration:'2h 45m',price:1999,originalPrice:2599,rating:4.2,reviews:1400,vehicleType:'Maruti Ertiga',seats:6,seatsAvailable:6,luggage:3,luxuryLevel:'Standard',comfortLevel:'Standard',facilities:['AC','Charging Port'],routeType:'Direct',groupType:['Family','Friends'],badge:null,image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',description:'Reliable outstation cab service to the Palace City.',availabilityDate:new Date('2026-07-08'),gallery:[]},
  { mode:'Cab',operator:'Savaari',from:'Jaipur',to:'Udaipur',departureTime:'Flexible',arrivalTime:'~6h',duration:'5h 30m',price:3999,originalPrice:4999,rating:4.4,reviews:920,vehicleType:'Toyota Fortuner',seats:6,seatsAvailable:6,luggage:5,luxuryLevel:'Premium',comfortLevel:'Business',facilities:['AC','Wi-Fi','Charging Port','Food','Luggage'],routeType:'One Stop',groupType:['Family','Couple','Friends'],badge:'Best Value',image:'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800',description:'SUV road trip through Rajasthan with scenic pit stops.',availabilityDate:new Date('2026-06-23'),gallery:[]},

  // ─── CAR RENTAL (4) ────────────────────────────────────────────
  { mode:'Car Rental',operator:'Zoomcar',from:'Goa',to:'Goa',departureTime:'Any',arrivalTime:'Self-drive',duration:'24h',price:1499,originalPrice:1999,rating:4.1,reviews:3100,vehicleType:'Hyundai i20',seats:4,seatsAvailable:10,luggage:2,luxuryLevel:'Standard',comfortLevel:'Economy',facilities:['AC','Charging Port'],routeType:'Direct',groupType:['Solo','Couple','Friends'],badge:'Cheapest',image:'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800',description:'Self-drive hatchback — perfect for beach hopping in Goa.',availabilityDate:new Date('2026-06-13'),gallery:[]},
  { mode:'Car Rental',operator:'Revv',from:'Bangalore',to:'Bangalore',departureTime:'Any',arrivalTime:'Self-drive',duration:'24h',price:2499,originalPrice:2999,rating:4.3,reviews:1700,vehicleType:'Mahindra XUV700',seats:7,seatsAvailable:5,luggage:5,luxuryLevel:'Premium',comfortLevel:'Standard',facilities:['AC','Charging Port','Luggage'],routeType:'Direct',groupType:['Family','Friends'],badge:'Family Friendly',image:'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800',description:'Premium SUV for family road trips around Bangalore.',availabilityDate:new Date('2026-07-04'),gallery:[]},
  { mode:'Car Rental',operator:'Avis India',from:'Delhi',to:'Delhi',departureTime:'Any',arrivalTime:'Self-drive',duration:'24h',price:5999,originalPrice:7499,rating:4.7,reviews:650,vehicleType:'Mercedes C-Class',seats:4,seatsAvailable:2,luggage:3,luxuryLevel:'Luxury',comfortLevel:'Luxury',facilities:['AC','Wi-Fi','Charging Port'],routeType:'Direct',groupType:['Couple','Corporate'],badge:'Luxury Pick',image:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',description:'Luxury sedan rental with roadside assistance and insurance.',availabilityDate:new Date('2026-06-21'),gallery:[]},
  { mode:'Car Rental',operator:'MyChoize',from:'Mumbai',to:'Mumbai',departureTime:'Any',arrivalTime:'Self-drive',duration:'24h',price:1799,originalPrice:2199,rating:4.0,reviews:2200,vehicleType:'Maruti Swift',seats:4,seatsAvailable:15,luggage:2,luxuryLevel:'Standard',comfortLevel:'Economy',facilities:['AC'],routeType:'Direct',groupType:['Solo','Couple'],badge:null,image:'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',description:'Affordable city run-around for exploring Mumbai independently.',availabilityDate:new Date('2026-07-06'),gallery:[]},

  // ─── BIKES (3) ─────────────────────────────────────────────────
  { mode:'Bike',operator:'Royal Brothers',from:'Goa',to:'Goa',departureTime:'Any',arrivalTime:'Self-ride',duration:'24h',price:799,originalPrice:999,rating:4.2,reviews:4500,vehicleType:'Royal Enfield Classic 350',seats:2,seatsAvailable:20,luggage:0,luxuryLevel:'Standard',comfortLevel:'Standard',facilities:['Luggage'],routeType:'Direct',groupType:['Solo','Couple','Friends'],badge:'Cheapest',image:'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800',description:'Iconic cruiser for Goan beach roads and countryside exploration.',featured:true,availabilityDate:new Date('2026-06-15'),gallery:[]},
  { mode:'Bike',operator:'Bounce',from:'Bangalore',to:'Bangalore',departureTime:'Any',arrivalTime:'Self-ride',duration:'24h',price:499,originalPrice:699,rating:3.9,reviews:6200,vehicleType:'Honda Activa 6G',seats:2,seatsAvailable:50,luggage:0,luxuryLevel:'Standard',comfortLevel:'Economy',facilities:[],routeType:'Direct',groupType:['Solo'],badge:'Cheapest',image:'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800',description:'Quick scooter rentals for zipping around Bangalore.',availabilityDate:new Date('2026-06-20'),gallery:[]},
  { mode:'Bike',operator:'Wicked Ride',from:'Manali',to:'Leh',departureTime:'06:00',arrivalTime:'Multi-day',duration:'2 Days',price:4999,originalPrice:6499,rating:4.8,reviews:1200,vehicleType:'Himalayan 450',seats:2,seatsAvailable:8,luggage:1,luxuryLevel:'Premium',comfortLevel:'Standard',facilities:['Luggage'],routeType:'Multi-Stop',groupType:['Solo','Friends','Couple'],badge:'Best Value',image:'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800',description:'Epic Manali-Leh adventure ride with backup support vehicle.',featured:true,availabilityDate:new Date('2026-07-01'),gallery:[]},

  // ─── LUXURY COACH (2) ──────────────────────────────────────────
  { mode:'Luxury Coach',operator:'Scania Metrolink',from:'Bangalore',to:'Goa',departureTime:'21:00',arrivalTime:'06:00',duration:'9h',price:1999,originalPrice:2499,rating:4.6,reviews:1800,vehicleType:'Scania Multi-Axle',seats:28,seatsAvailable:5,luggage:30,luxuryLevel:'Luxury',comfortLevel:'Business',facilities:['AC','Wi-Fi','Charging Port','Sleeper','Food','Luggage'],routeType:'Direct',groupType:['Couple','Friends','Corporate'],badge:'Best Value',image:'https://images.unsplash.com/photo-1570125909517-53cb21c89ff2?w=800',description:'European luxury coach with semi-sleeper seats, HVAC and pantry.',availabilityDate:new Date('2026-06-24'),gallery:[]},
  { mode:'Luxury Coach',operator:'Neeta Volvo',from:'Mumbai',to:'Bangalore',departureTime:'19:00',arrivalTime:'09:00',duration:'14h',price:2499,originalPrice:2999,rating:4.4,reviews:2600,vehicleType:'Volvo 9400',seats:30,seatsAvailable:10,luggage:25,luxuryLevel:'Premium',comfortLevel:'Standard',facilities:['AC','Wi-Fi','Charging Port','Sleeper'],routeType:'One Stop',groupType:['Solo','Friends','Corporate'],badge:null,image:'https://images.unsplash.com/photo-1547638375-ebf04735d792?w=800',description:'Reliable multi-axle Volvo sleeper with one refreshment stop.',availabilityDate:new Date('2026-07-07'),gallery:[]},
];

const seed = async () => {
  try {
    // 1. Optional Backup - not strictly required if we are just upserting, but a good practice
    // We can skip explicit backup file creation and just use safe upsert to avoid data loss.
    console.log('🔄  Starting safe upsert for transportation data...');

    // 2. Map seedData to include new primary fields and perform upsert
    let upsertedCount = 0;
    
    for (const item of seedData) {
      // Map for backward compatibility and new schema requirements
      const dataToUpsert = {
        ...item,
        type: item.mode, // new primary field
        providerName: item.operator, // new primary field
      };

      // Perform upsert based on the new primary fields plus from/to to uniquely identify routes
      const result = await Transportation.updateOne(
        { 
          type: dataToUpsert.type, 
          providerName: dataToUpsert.providerName,
          from: dataToUpsert.from,
          to: dataToUpsert.to,
          departureTime: dataToUpsert.departureTime
        },
        { $set: dataToUpsert },
        { upsert: true }
      );
      
      if (result.upsertedCount > 0 || result.modifiedCount > 0) {
        upsertedCount++;
      }
    }

    console.log(`✅ Upserted/Modified ${upsertedCount} transportation records safely`);
    process.exit(0);
  } catch (err) {
    console.error('❌ Seed failed:', err);
    process.exit(1);
  }
};

seed();
