import mongoose from 'mongoose';

const itinerarySchema = new mongoose.Schema({
  day: { type: Number, required: true },
  title: { type: String, required: true },
  desc: { type: String, required: true },
  activities: { type: [String], default: [] }
}, { _id: false });

const packageSchema = new mongoose.Schema({
  name:       { type: String, required: true },
  location:   { type: String },
  duration:   { type: String, required: true },
  category:   { type: String, default: 'Adventure' }, // Will be dynamic (Beach, Mountain, etc.)
  image:      { type: String, required: true },
  heroImage:  { type: String },
  imageSource: { type: String },
  imageUpdatedAt: { type: Date },
  gallery:    { type: [String], default: [] },
  imagePool:  { type: [String], default: [] },
  price:      { type: Number, required: true },
  originalPrice: { type: Number },
  discount:   { type: String },
  rating:     { type: Number, default: 0 },
  reviews:    { type: Number, default: 0 },
  popularity: { type: Number, default: 0 },
  
  description: { type: String },
  tagline:     { type: String },
  bestSeason:  { type: String },
  idealFor:    { type: [String], default: [] },
  
  highlights:  { type: [String], default: [] },
  itinerary:   { type: [itinerarySchema], default: [] },
  included:    { type: [String], default: [] },
  excluded:    { type: [String], default: [] },
  
  activities:  { type: [String], default: [] },
  hotelsInfo:  { type: [String], default: [] }, // Summarized hotel info generated by AI
  transportDesc: { type: String }, // Description of transport
  meals:       { type: [String], default: [] }, // E.g., ['Breakfast', 'Dinner']
  
  cancellationPolicy: { type: String },
  bookingPolicy:      { type: String },
  mapLocation:        { type: String }, // coordinates or search term
  travelTips:         { type: [String], default: [] },
  faqs:               { type: [{ q: String, a: String }], default: [] },

  isAIGenerated: { type: Boolean, default: false },

  // New fields for advanced filtering and badging
  groupType:     { type: [String], default: [] }, // e.g. ["Solo", "Couple", "Family", "Friends", "Corporate"]
  inclusions:    { type: [String], default: [] }, // e.g. ["Flights", "Hotel", "Meals", "Transfers", "Sightseeing", "Visa", "Guide"]
  travelMonths:  { type: [String], default: [] }, // e.g. ["January", "February", ...]
  comfortLevel:  { type: String, enum: ["Budget", "Standard", "Deluxe", "Luxury"], default: "Standard" },
  badge:         { type: String, default: null },
  isEcoFriendly: { type: Boolean, default: false },
  views:         { type: Number, default: 0 },
  isActive:      { type: Boolean, default: true }
}, { timestamps: true });

// Create text index for search
packageSchema.index({ name: 'text', location: 'text', category: 'text' });

// Create compound indexes for filtering and sorting
packageSchema.index({ category: 1, groupType: 1 });
packageSchema.index({ category: 1, travelMonths: 1 });
packageSchema.index({ category: 1, comfortLevel: 1 });
packageSchema.index({ price: 1, rating: 1 });

export default mongoose.model('Package', packageSchema);
